version: "3"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DIR}:/var/lib:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    networks:
      - default
    container_name: cam_mysql
    restart: always
networks:
  default:
